schema_version = "1.0.0"
name = "Auto Node Outputs"
author = "claudiomarks"
version = "1.6.5"
id = "auto_node_outputs"
tagline = "Automatically connect ViewLayers to File Output nodes"
maintainer = "claudiomarks"
type = "add-on"
tags = ["Compositing", "Render"]
blender_version_min = "4.2.0"
license = ["SPDX:GPL-3.0-or-later"]
copyright = [
    "2025 Histeria"
]
include = [
    "src/**/*.py",
    "README.md",
    "__init__.py",
]

# Files to exclude from the addon distribution
exclude = [
    "**/__pycache__/**",
    "**/.git/**",
    "**/.github/**",
]